#
# Chapter 2 Experiments
#

# This is used to generate Figure 2.3
["chapters/02_modelling/example_neuron.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = ["example_neuron_voltage_traces.svg"]

["chapters/02_modelling/granule_cell_response_curves.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = ["granule_cell_response_curves.npy"]
is_multithreaded = true

["chapters/02_modelling/low_firing_rate_dynamics_sweep.py"]
#commit = "0c58889ef3b523c5a7cf1402ab5a5ea2fe19da1b" # Short experiment
#commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb" # Long experiment
commit = "c915cb4d474f1880378e00d5e79320364d37a9c9"  # Very long experiment
dockerfile = "experiments_base"
generates = ["low_firing_rates_dynamics_sweep.h5"]
is_multithreaded = true

["chapters/02_modelling/spiking_neurons_ramp.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
runs = [
	{
		args=["--neuron", "HH", "--tar", "hodgkin_huxley_ramp.npz"],
		generates=["hodgkin_huxley_ramp.npz"]
	},
	{
		args=["--neuron", "HH", "--T", "0.5", "--J", "0.25", "--no_skew", "--tar", "hodgkin_huxley_ramp_short.npz"],
		generates=["hodgkin_huxley_ramp_short.npz"]
	},
	{
		args=["--neuron", "LIF", "--tar", "lif_ramp.npz"],
		generates=["lif_ramp.npz"]
	},
	{
		args=["--neuron", "LIF", "--T", "0.5", "--J", "0.25", "--no_skew", "--tar", "lif_ramp_short.npz"],
		generates=["lif_ramp_short.npz"]
	}
]

#
# Chapter 3 Experiments
#

["chapters/03_nlif/average_som_pot.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "average_som_pot.h5"
is_multithreaded = true

["chapters/03_nlif/bias_decoding_impact.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "bias_decoding_impact.h5"
is_multithreaded = true

["chapters/03_nlif/inhibitory_interneurons.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "inhibitory_interneurons.h5"
is_multithreaded = true

["chapters/03_nlif/nef_noise_visualisation.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nef_noise_visualisation.h5"
is_multithreaded = true

["chapters/03_nlif/nonnegative_experiment.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nonnegative_experiment.h5"
is_multithreaded = true

["chapters/03_nlif/nonnegative_factorisation.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nonnegative_factorisation.h5"
is_multithreaded = true

["chapters/03_nlif/nonnegative_sparsity.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nonnegative_sparsity.h5"
is_multithreaded = true

["chapters/03_nlif/two_comp_weights_examples_statistics.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "two_comp_weights_examples_statistics.h5"
is_multithreaded = true

["chapters/03_nlif/subthreshold_relaxation_experiments_auto_reg.py"]
commit = "cae54b7092a5630669a0572f2661b01872d3c4f5"
dockerfile = "experiments_base"
generates = "subthreshold_relaxation_experiment_auto_reg.h5"
is_multithreaded = true

["chapters/ZC_data/two_comp_benchmark_functions_regularisation_filter_sweep.py"]
commit = "ff949951361dba867e7a1bcc636f368960dc021f"
dockerfile = "experiments_base"
generates = "two_comp_benchmark_functions_regularisation_filter_sweep.h5"
is_multithreaded = true

