#
# Chapter 2 Experiments
#

# This is used to generate Figure 2.3
["chapters/02_modelling/example_neuron.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = ["example_neuron_voltage_traces.svg"]

["chapters/02_modelling/granule_cell_response_curves.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = ["granule_cell_response_curves.npy"]
is_multithreaded = true

["chapters/02_modelling/low_firing_rate_dynamics_sweep.py"]
#commit = "0c58889ef3b523c5a7cf1402ab5a5ea2fe19da1b" # Short experiment
#commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb" # Long experiment
commit = "c915cb4d474f1880378e00d5e79320364d37a9c9"  # Very long experiment
dockerfile = "experiments_base"
generates = ["low_firing_rates_dynamics_sweep.h5"]
is_multithreaded = true

["chapters/02_modelling/spiking_neurons_ramp.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
runs = [
	{
		args=["--neuron", "HH", "--tar", "hodgkin_huxley_ramp.npz"],
		generates=["hodgkin_huxley_ramp.npz"]
	},
	{
		args=["--neuron", "HH", "--T", "0.5", "--J", "0.25", "--no_skew", "--tar", "hodgkin_huxley_ramp_short.npz"],
		generates=["hodgkin_huxley_ramp_short.npz"]
	},
	{
		args=["--neuron", "LIF", "--tar", "lif_ramp.npz"],
		generates=["lif_ramp.npz"]
	},
	{
		args=["--neuron", "LIF", "--T", "0.5", "--J", "0.25", "--no_skew", "--tar", "lif_ramp_short.npz"],
		generates=["lif_ramp_short.npz"]
	}
]

#
# Chapter 3 Experiments
#

["chapters/03_nlif/average_som_pot.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "average_som_pot.h5"
is_multithreaded = true

["chapters/03_nlif/bias_decoding_impact.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "bias_decoding_impact.h5"
is_multithreaded = true

["chapters/03_nlif/inhibitory_interneurons.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "inhibitory_interneurons.h5"
is_multithreaded = true

["chapters/03_nlif/nef_noise_visualisation.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nef_noise_visualisation.h5"
is_multithreaded = true

["chapters/03_nlif/nonnegative_experiment.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nonnegative_experiment.h5"
is_multithreaded = true

["chapters/03_nlif/nonnegative_factorisation.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nonnegative_factorisation.h5"
is_multithreaded = true

["chapters/03_nlif/nonnegative_sparsity.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "nonnegative_sparsity.h5"
is_multithreaded = true

["chapters/03_nlif/two_comp_weights_examples_statistics.py"]
commit = "dd02a4eb75cc4d3a3d8da7dd7e12bef3a3be3dcb"
dockerfile = "experiments_base"
generates = "two_comp_weights_examples_statistics.h5"
is_multithreaded = true

["chapters/03_nlif/subthreshold_relaxation_experiments_auto_reg.py"]
commit = "cae54b7092a5630669a0572f2661b01872d3c4f5"
dockerfile = "experiments_base"
generates = "subthreshold_relaxation_experiment_auto_reg.h5"
is_multithreaded = true

["chapters/03_nlif/two_comp_2d_frequency_sweep.py"]
commit = "a4de81d3f32301a75aacfc85c6b58b75b1d5e2a9"
dockerfile = "experiments_base"
generates = "two_comp_2d_frequency_sweep.h5"
is_multithreaded = true

["chapters/03_nlif/two_comp_2d_frequency_sweep_network.py"]
commit = "404b176846516c031841cebd293a0b99b14e5965"
dockerfile = "experiments_base"
generates = "two_comp_2d_frequency_sweep_network.h5"
is_multithreaded = true

["chapters/03_nlif/two_comp_2d_benchmark_functions_network.py"]
commit = "e6362d1031b43c252404b151edfa70b14e900b00"
dockerfile = "experiments_base"
generates = "two_comp_2d_benchmark_functions_network.h5"
is_multithreaded = true

["chapters/03_nlif/dendritic_computation_fourier_example.py"]
commit = "7f91dbbb60d095a08676f170dd73d3141189bbdf"
dockerfile = "experiments_base"
runs = [
	{
		args=["--d", "5"],
		generates=["dendritic_computation_fourier_example_d5.h5"]
	},
	{
		args=["--d", "9"],
		generates=["dendritic_computation_fourier_example_d9.h5"]
	},
	{
		commit="9dbacb10bba9813c7c874c1566ba93e0e8cb81f7",
		args=["--rho", "0.5"],
		generates=["dendritic_computation_fourier_example_rho050.h5"]
	},
]
is_multithreaded = true

["chapters/03_nlif/decode_basis_functions.py"]
commit = "ac295d81b5839148829fd0c15aeb43f92562aeb3"
dockerfile = "experiments_base"
generates = "decode_basis_functions.h5"
is_multithreaded = true

["chapters/03_nlif/nlif_parameter_optimisation_comparison.py"]
commit = "b19625347233a249a79b427bd5911e40b8aae246"
dockerfile = "experiments_base"
generates = "nlif_parameter_optimisation_comparison.h5"
is_multithreaded = true

["chapters/03_nlif/nlif_weight_optimisation_comparison.py"]
commit = "9d1d744ff6b3979712cfed1d97105f981e082c55"
dockerfile = "experiments_base"
generates = "nlif_weight_optimisation_comparison.h5"
is_multithreaded = true

["chapters/03_nlif/nlif_parameter_contours.py"]
commit = "392d7bc37fa2899971625d7e88a61a7a8415f3b8"
dockerfile = "experiments_base"
generates = [
	"nlif_params_contour_two_comp_lif.npz",
	"nlif_params_contour_three_comp_lif_1.npz",
	"nlif_params_contour_three_comp_lif_2.npz",
	"nlif_params_contour_four_comp_lif_1.npz",
	"nlif_params_contour_four_comp_lif_2.npz",
	"nlif_params_contour_four_comp_lif_3.npz",
]
is_multithreaded = true

["chapters/03_nlif/nlif_frequency_sweep.py"]
commit = "7692920e4275ed7dacc4746660101bda3217f7f1"
dockerfile = "experiments_base"
runs = [
	{
		args=["0"],
		generates=["nlif_frequency_sweep_0.h5"]
	},
	{
		args=["1"],
		generates=["nlif_frequency_sweep_1.h5"]
	},
	{
		args=["2"],
		generates=["nlif_frequency_sweep_2.h5"]
	},
	{
		args=["3"],
		generates=["nlif_frequency_sweep_3.h5"]
	},
	{
		args=["4"],
		generates=["nlif_frequency_sweep_4.h5"]
	},
	{
		args=["5"],
		generates=["nlif_frequency_sweep_5.h5"]
	},
	{
		args=["6"],
		generates=["nlif_frequency_sweep_6.h5"]
	},
	{
		args=["7"],
		generates=["nlif_frequency_sweep_7.h5"]
	},
	{
		args=["8"],
		generates=["nlif_frequency_sweep_8.h5"]
	},
	{
		args=["9"],
		generates=["nlif_frequency_sweep_9.h5"]
	},
]
is_multithreaded = true

["chapters/03_nlif/nlif_decode_multiplication_example.py"]
commit = "9d1d744ff6b3979712cfed1d97105f981e082c55"
dockerfile = "experiments_base"
generates = "nlif_decode_multiplication_example.npz"
is_multithreaded = false

["chapters/03_nlif/nlif_2d_benchmark_functions_network.py"]
commit = "fd8c372f56bc61d32ef49c3abb8c6679f6ca2a2f"
dockerfile = "experiments_base"
runs = [
	{
		args=["0"],
		generates=["nlif_2d_benchmark_functions_network_0.h5"]
	},
	{
		args=["1"],
		generates=["nlif_2d_benchmark_functions_network_1.h5"]
	},
	{
		args=["2"],
		generates=["nlif_2d_benchmark_functions_network_2.h5"]
	},
	{
		args=["3"],
		generates=["nlif_2d_benchmark_functions_network_3.h5"]
	},
	{
		args=["4"],
		generates=["nlif_2d_benchmark_functions_network_4.h5"]
	},
	{
		args=["5"],
		generates=["nlif_2d_benchmark_functions_network_5.h5"]
	},
	{
		args=["6"],
		generates=["nlif_2d_benchmark_functions_network_6.h5"]
	},
	{
		args=["7"],
		generates=["nlif_2d_benchmark_functions_network_7.h5"]
	},
	{
		args=["8"],
		generates=["nlif_2d_benchmark_functions_network_8.h5"]
	},
	{
		args=["9"],
		generates=["nlif_2d_benchmark_functions_network_9.h5"]
	},
]
is_multithreaded = true

["chapters/03_nlif/nlif_three_comp_multiplication_spike_data.py"]
commit = "7b5a2e3f04333404e13bc8a0485c4d08e7ba3b16"
dockerfile = "experiments_base"
runs = [
	{
		args=[],
		generates=["nlif_three_comp_multiplication_spike_data.pkl"]
	},
	{
		args=["default_icepts"],
		generates=["nlif_three_comp_multiplication_spike_data_default_icepts.pkl"]
	}
]
is_multithreaded = true

["chapters/05_cerebellum/generate_cerebellum_detailed_neurons_example.py"]
commit = "703545981eb0ffbe47f478d0400200a0755eceaa"
dockerfile = "experiments_base"
generates = "cerebellum_detailed_neurons_example.h5"
is_multithreaded = true

["chapters/05_cerebellum/generate_benchmark_data.py"]
commit = "8e5d2a0dc30a88c3b6911d3e866f9b660ec09422"
dockerfile = "experiments_base"
is_multithreaded = true
generates = [
	"weights.tar",
	"pl_direct.h5",
	"pl_single_population.h5",
	"pl_two_populations_dales_principle_detailed.h5",
	"pl_two_populations_dales_principle.h5",
	"pl_two_populations.h5",
	"sweep_n_golgi_granule_convergence_wn_two_populations_dales_principle_detailed.h5",
	"sweep_n_pcn_granule_convergence_wn_two_populations_dales_principle_detailed.h5",
	"sweep_tau_wn_two_populations_dales_principle_detailed.h5",
	"wn_direct.h5",
	"wn_single_population.h5",
	"wn_two_populations_dales_principle_detailed.h5",
	"wn_two_populations_dales_principle.h5",
	"wn_two_populations.h5"
]

["chapters/05_cerebellum/generate_blink_trial_data.py"]
commit = "f9d929f22dfa2c972c7cb3a84c28842dee804c87"
dockerfile = "experiments_base"
generates = [
	"blink_trial_0.npz",
	"blink_trial_1.npz",
	"blink_trial_2.npz",
	"blink_trial_3.npz",
	"blink_trial_4.npz",
	"blink_trial_5.npz",
]
is_multithreaded = true

["chapters/ZC_data/two_comp_benchmark_functions_regularisation_filter_sweep.py"]
commit = "e68c291667996e632acd61452f38f73af971727b"
dockerfile = "experiments_base"
generates = "two_comp_benchmark_functions_regularisation_filter_sweep.h5"
is_multithreaded = true

["chapters/ZC_data/two_comp_2d_regularisation_sweep.py"]
commit = "2fd36947437edb7318c136bb2486f059d3fef58c"
dockerfile = "experiments_base"
generates = "two_comp_2d_regularisation_sweep.h5"
is_multithreaded = true

